In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('flight.csv')

In [3]:
df.shape

(30, 9)

In [4]:
df.sample(8)

,flight_id,airline,source_city,destination_city,departure_time,stops,duration_hours,days_left,price
1,2,AirIndia,Mumbai,Bangalore,Evening,1-stop,5.0,10,6400
18,19,AirAsia,Bangalore,Delhi,Evening,non-stop,2.7,16,5100
13,14,Vistara,Bangalore,Chennai,Afternoon,non-stop,1.2,19,3600
26,27,SpiceJet,Delhi,Mumbai,Afternoon,non-stop,2.4,29,5000
25,26,Vistara,Bangalore,Mumbai,Morning,non-stop,1.8,26,4400
12,13,AirAsia,Mumbai,Delhi,Night,non-stop,2.4,14,5000
2,3,SpiceJet,Delhi,Chennai,Afternoon,1-stop,4.5,7,5900
3,4,Vistara,Kolkata,Delhi,Morning,non-stop,2.0,20,4500

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   flight_id         30 non-null     int64
 1   airline           30 non-null     object
 2   source_city       30 non-null     object
 3   destination_city  30 non-null     object
 4   departure_time    30 non-null     object
 5   stops             30 non-null     object
 6   duration_hours    30 non-null     float64
 7   days_left         30 non-null     int64
 8   price             30 non-null     int64
dtypes: float64(1), int64(3), object(5)
memory usage: 2.2+ KB

In [6]:
df.isnull().sum()

flight_id           0
airline             0
source_city         0
destination_city    0
departure_time      0
stops               0
duration_hours      0
days_left           0
price               0
dtype: int64

In [7]:
df.describe()

       flight_id  duration_hours  days_left        price
count  30.000000       30.000000  30.000000    30.000000
mean   15.500000        3.580000  15.533333  5483.333333
std     8.803408        1.696325   7.762569   984.389653
min     1.000000        1.200000   4.000000  3600.000000
25%     8.250000        2.325000   9.250000  4825.000000
50%    15.500000        2.850000  14.500000  5300.000000
75%    22.750000        4.750000  21.750000  6100.000000
max    30.000000        8.000000  30.000000  7500.000000

In [8]:
df.duplicated().sum()

np.int64(0)